# Generated by Django 5.0.1 on 2024-01-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_name',
            new_name='username',
        ),
    ]
